### ISSUE TITLE
Can't throw a string

### ISSUE THREAD

**Issue by mcabbott** [BioTurboNick/AbbreviatedStackTraces.jl#1]
Perhaps this is an abuse, but it does normally work:
```julia
julia> throw("msg")
ERROR: 
SYSTEM (REPL): showing an error caused an error
ERROR: MethodError: Cannot `convert` an object of type String to an object of type Exception
Closest candidates are:
  convert(::Type{T}, ::T) where T at essentials.jl:205
Use `err` to retrieve the full stack trace.

julia> err
ERROR: MethodError: Cannot `convert` an object of type String to an object of type Exception
Closest candidates are:
  convert(::Type{T}, ::T) where T at essentials.jl:205
Stacktrace:
  [1] AbbreviatedStackTraces.ExceptionInfo(error::String, stack::Vector{Base.StackTraces.StackFrame})
    @ AbbreviatedStackTraces ~/.julia/packages/AbbreviatedStackTraces/IBaVh/src/AbbreviatedStackTraces.jl:21
```

**Comment by BioTurboNick** [comment]
~~Ack! That's because I had to hack some things for the package. The original worked. If I can figure out how to hook the REPL the right way, or replace it? Not sure what's possible from a package.~~ Nevermind, got it.

**Comment by mcabbott** [comment]
Apparently adding a method `AbbreviatedStackTraces.ExceptionInfo(ex::String, bt) = AbbreviatedStackTraces.ExceptionInfo(error(ex), bt)` does not work.

**Comment by BioTurboNick** [comment]
Yeah it just needed to accept Any for the first argument.

**Comment by BioTurboNick** [comment]
@mcabbott fyi I ported over the full behavior, figured out what I was doing wrong re: the REPL. You should be able to fully exercise it now.
