### ISSUE TITLE
Remove type information?

### ISSUE THREAD

**Issue by antoine-levitt** [BioTurboNick/AbbreviatedStackTraces.jl#12]
See discussion in julia issue.

**Comment by BioTurboNick** [comment]
Might be worthwhile for the short view. Inlined frames already don't show the signature at all

**Comment by antoine-levitt** [comment]
If we don't print the signature at all, we can just print each frame in one line, which would be super cool (finally stacktraces on a single screen!)

**Comment by BioTurboNick** [comment]
![image](https://user-images.githubusercontent.com/1438610/115971635-8e96a400-a517-11eb-9443-79f783e92100.png)


I have it in a separate branch, `remove_types`, just because it's a bit more drastic change.

**Comment by mcabbott** [comment]
I think some type information is super-useful, but seldom every detail. The current printing is meant to highlight the outermost type, and maybe the obvious hook is something like this?
```
map(sqrt, fill((fill((fill((:a,'a',"a"),3),),4),),5))

@eval Base function print_type_stacktrace(io, type; color=:normal)
    str = sprint(show, type, context=io)
    i = findfirst('{', str)
    if i === nothing || !get(io, :backtrace, false)::Bool
        printstyled(io, str; color=color)
    else
        printstyled(io, str[1:prevind(str,i)]; color=color)
        if length(str) - i < 20  # then show the whole type parameter
            printstyled(io, str[i:end]; color=:light_black)
        else
            printstyled(io, str[i:nextind(str,i,15)], "...}"; color=:light_black)
        end
    end
end

map(sqrt, fill((fill((fill((:a,'a',"a"),3),),4),),5))  # not a great example!
```

**Comment by antoine-levitt** [comment]
This could make sense; alternatively one could just print just the abstract type, without its whole parametric expression; that should be enough in most cases. Though for me the idea of this package (of having one "simple stacktrace" with the full one available) pleads for the simplest option of not printing anything. Once you get the rough idea of where the trouble is, you can just "zoom in" on the full info. For the rough idea, you probably don't need type info, just to track the control flow of who calls who. It's true that some code just can't be understood without type info, but is that really the majority?

**Comment by mcabbott** [comment]
> for me the idea of this package (of having one "simple stacktrace" with the full one available) pleads for the simplest option 

My take is more that, if this aims to get into Base, then it should make few & relatively well-justified changes to solve problems. Trimming the type parameters means you won't accidentally get many screenfuls, but you also won't have to learn to scan two quite different styles of printing. 

The reason I think types are often useful is that Julia so often has a dozen different things called `fun`. Although sometimes it would be more useful to have the method's signature than the concrete types, or both, somehow... right now you need to follow the path to see that.

**Comment by BioTurboNick** [comment]
> > for me the idea of this package (of having one "simple stacktrace" with the full one available) pleads for the simplest option
> 
> My take is more that, if this aims to get into Base, then it should make few & relatively well-justified changes to solve problems. Trimming the type parameters means you won't accidentally get many screenfuls, but you also won't have to learn to scan two quite different styles of printing.

Yeah, I'm taking this to heart. The more changes we propose, the harder the ask is going to be. If we can address the major pain points, that's a great move forward.

**Comment by antoine-levitt** [comment]
> Trimming the type parameters means you won't accidentally get many screenfuls, but you also won't have to learn to scan two quite different styles of printing.

You already have to deal with lots more styles than that: inlined functions and macros both print differently than "regular" functions for instance.

> My take is more that, if this aims to get into Base, then it should make few & relatively well-justified changes to solve problems.

Julia stacktraces right now are basically the best they can be given the (strong) constraint that they have to include the maximum information possible. The proposal here is to have two types of stacktraces: an easy one and a complete one. The easy stacktrace should not try to replace the complete one: rather, it should be one that is enough most of the time, and is *very* easy to skim through, so you don't lose time if the information you're looking for is not in the easy stacktrace but in the complete one. I'd even say that the less the easy stacktrace looks like the complete one, the better! That way they'll be easier to distinguish.

So why not just simplify to the maximum? No signatures, one line frames, just plain old `[n] function_name @ Module path/file.jl:n`? (possibly not even full file paths?)

**Comment by antoine-levitt** [comment]
Also I think the way of making this in Base is not by incremental PRs but just having this package be super useful and widely used, so that the quirks get ironed out and it becomes clear through practice what is helpful and what isn't. Then it can be backported (possibly in a watered down version) to Base.

**Comment by BioTurboNick** [comment]
I hear you... My intention is to try to get something in Base sooner than later, because I'd want newer people to the language to benefit. If we want to think about two tracks though, one for "likely to get in Base" and another for "most concise possible", that may be a good way to proceed?

Someone mentioned there's an option mechanism for the REPL. I haven't looked into that. Could the concise one be put behind one of those, for now? That way we have a single branch and package for both options, and can work on them in parallel.

**Comment by BioTurboNick** [comment]
I found `Base.active_repl.options.iocontext`, but it seems to only be used when the REPL directly calls a `show` method, not when an exception is hit. Might be because it goes through `stderr` instead.

**Comment by BioTurboNick** [comment]
I added an environment variable to turn the minimal (typeless, 1 line) mode on/off: `ENV["JULIA_STACKTRACE_MINIMAL"] = true`/`false`

**Comment by BioTurboNick** [comment]
Since the typeless 1-line version now exists as an option, I'm going to close this. Removing any type info from the main version, even to abbreviate, seems like a hard ask for base. If someone wants to put forward a PR for a type-light version, that'd be cool. Maybe someone who uses/develops a package with huge type information could make or evaluate such a proposal? I don't think I'll consider it a priority for myself to work on though.

**Comment by antoine-levitt** [comment]
The 1-line version is so nice it's ridiculous:
```
   [1-3] ⋮ [internal frames] @ [inlined methods]
     [4] eigen @ /buildworker/worker/package_linux64/build/usr/share/julia/stdlib/v1.6/LinearAlgebra/src/symmetric.jl:678 [inlined]
     [5] macro expansion @ ~/.julia/dev/DFTK/src/eigen/lobpcg_hyper_impl.jl:59 [inlined]
     [6] ⋮ [internal frame] @ DFTK
     [7] timeit @ TimerOutputs ~/.julia/packages/TimerOutputs/4QAIk/src/TimerOutput.jl:285
     [8] rayleigh_ritz @ DFTK ~/.julia/packages/TimerOutputs/4QAIk/src/TimerOutput.jl:236
     [9] macro expansion @ ~/.julia/dev/DFTK/src/eigen/lobpcg_hyper_impl.jl:288 [inlined]
 [10-11] ⋮ [internal frames] @ DFTK, TimerOutputs
    [12] LOBPCG @ ~/.julia/packages/TimerOutputs/4QAIk/src/TimerOutput.jl:236 [inlined]
    [13] lobpcg_hyper @ DFTK ~/.julia/dev/DFTK/src/eigen/diag_lobpcg_hyper.jl:9
    [14] diagonalize_all_kblocks @ DFTK ~/.julia/dev/DFTK/src/eigen/diag.jl:48
    [15] next_density @ DFTK ~/.julia/dev/DFTK/src/scf/self_consistent_field.jl:25
    [16] fixpoint_map @ DFTK ~/.julia/dev/DFTK/src/scf/self_consistent_field.jl:105
    [17] 503 @ DFTK ~/.julia/dev/DFTK/src/scf/scf_solvers.jl:18
 [18-24] ⋮ [internal frames] @ NLSolversBase, NLsolve, [inlined methods]
    [25] nlsolve @ NLsolve ~/.julia/packages/NLsolve/gJL1I/src/nlsolve/nlsolve.jl:52
    [26] fp_solver @ ~/.julia/dev/DFTK/src/scf/scf_solvers.jl:18 [inlined]
    [27] macro expansion @ ~/.julia/dev/DFTK/src/scf/self_consistent_field.jl:153 [inlined]
    [28] ⋮ [internal frame] @ DFTK
    [29] timeit @ TimerOutputs ~/.julia/packages/TimerOutputs/4QAIk/src/TimerOutput.jl:285
    [30] self_consistent_field @ DFTK ~/.julia/packages/TimerOutputs/4QAIk/src/TimerOutput.jl:236
    [31] top-level scope @ ~/.julia/dev/DFTK/examples/silicon.jl:16
    [32] include @ Base.MainInclude ./client.jl:444
```
Skipping frames works very well for the "normal" [18]-[24] and [1]-[3]. Not so much for the macros expansions...

**Comment by antoine-levitt** [comment]
Actually, the improvement in usability by having 1-line stacktraces with just method names is much larger than that by skipping frames. That kind of shifts priorities for me.

**Comment by BioTurboNick** [comment]
It is nice!

**Comment by BioTurboNick** [comment]
With the macro expansions, what do you think it should look like? Is there a rule that would help there?

**Comment by antoine-levitt** [comment]
> With the macro expansions, what do you think it should look like? Is there a rule that would help there?

Stacktraces with macros are just too screwed up...
