### ISSUE TITLE
Trim `error(s::String)` and `top-level scope`?

### ISSUE THREAD

**Issue by mcabbott** [BioTurboNick/AbbreviatedStackTraces.jl#16]
These two are unrelated, but always seem like useless information. Why not print only `[2]` here?
```julia
julia> f(x) = x>0 ? x : error("negative!");

julia> f(-1)
ERROR: negative!
Stacktrace:
 [1] error(s::String)
   @ Base ./error.jl:33
 [2] f(x::Int64)
   @ Main ./REPL[16]:1
 [3] top-level scope
   @ REPL[17]:1
```

**Comment by mcabbott** [comment]
Which, xref #1, is why `throw`ing a string sometimes seems like a good idea. Note the following bug, BTW:
```
julia> f(x) = x>0 ? x : throw("negative!");

julia> f(-1)
ERROR: "negative!"
Stacktrace:
 [1] f(x::Int64)
   @ Main ./REPL[19]:1
 [2] top-level scope
   @ REPL[20]:1

julia> throw("negative!")
ERROR: "negative!"
Stacktrace:

SYSTEM (REPL): showing an error caused an error
ERROR: BoundsError: attempt to access 1-element Vector{Any} at index [0]
Stacktrace:
  [1] getindex
    @ ./array.jl:801 [inlined]
  [2] maybeview
    @ ./views.jl:134 [inlined]
  [3] show_compact_backtrace(io::IOContext{Base.TTY}, trace::Vector{Any}; print_linebreaks::Bool)
    @ AbbreviatedStackTraces ~/.julia/packages/AbbreviatedStackTraces/LvY16/src/AbbreviatedStackTraces.jl:104
```

**Comment by BioTurboNick** [comment]
I thought about top-level scope and initially did. I could go either way. I added it back because it sometimes is different, such as with a macro like `@btime`. So removed, it might look like the below.

(ignore the specific formatting, I've been playing around with it)

```
@btime plot([1,2,3], seriestype=:blah)
ERROR: The backend must not support the series type Val{:blah}, and there isn't a series recipe defined.
Stacktrace:
   [1-7] ⋮
       @ Base RecipesPipeline Plots
     [8] plot(args::Any; kw::Base.Pairs{Symbol, V, Tuple{Vararg{Symbol, N}}, NamedTuple{names, T}} where {V, N, names, T<:Tuple{Vararg{Any, N}}})
       @ Plots ~/.julia/packages/Plots/kyYZF/src/plot.jl:58
  [9-17] ⋮
       @ Main BenchmarkTools
```

Is that okay, you think?

As for `error`... Yeah we could detect the error-generating function names in base and remove those.


(Thanks for the bug find!)

**Comment by mcabbott** [comment]
I never noticed that `top-level scope` sometimes has a path like that. Is it useful sometimes?

Re `error`, I think it's just this one function really, but it's commonly used. It gets hidden already in many cases like your `plot` example. But when not, like my `f`, I guess the awkward question is whether to still give it a number (and start from `[2]`), or pop it from the stacktrace entirely (and hence change numbers of other entries)? Hiding it with the same `⋮` story as elsewhere isn't going to help, for just one line.

**Comment by BioTurboNick** [comment]
> I never noticed that `top-level scope` sometimes has a path like that. Is it useful sometimes?

I don't know :-) Guess we could just drop it and find out if someone complains.

> Re `error`, I think it's just this one function really, but it's commonly used. It gets hidden already in many cases like your `plot` example. But when not, like my `f`, I guess the awkward question is whether to still give it a number (and start from `[2]`), or pop it from the stacktrace entirely (and hence change numbers of other entries)? Hiding it with the same `⋮` story as elsewhere isn't going to help, for just one line.

That might not be a bad idea. The way it works now, the REPL frames get scrubbed out in `display_error` before being passed to the `showerror` functions. The same could be done for `error`.

**Comment by BioTurboNick** [comment]
The issue that `@btime` has, I think, is that there's otherwise no indication that you're executing anything inside the BenchmarkTools package. Maybe only a REPL-based top-level scope should be removed.

**Comment by BioTurboNick** [comment]
Implemented

**Comment by mcabbott** [comment]
Thanks!

Works nicely on Julia nightly, maybe worth noting that on 1.6 (which worked earlier) there's now an error:
```
julia> f(x) = x>0 ? x : error("negative!");

julia> f(-1)
ERROR: negative!
Stacktrace:
   [1] 
SYSTEM (REPL): showing an error caused an error
ERROR: MethodError: no method matching show_tuple_as_call(::IOContext{Base.TTY}, ::Symbol, ::Type{Tuple{typeof(f), Int64}}; demangle=true, argnames=[Symbol("#self#"), :x])
Closest candidates are:
  show_tuple_as_call(::IO, ::Symbol, ::Type) at show.jl:2218 got unsupported keyword arguments "demangle", "argnames"
  show_tuple_as_call(::IO, ::Symbol, ::Type, ::Any) at show.jl:2218 got unsupported keyword arguments "demangle", "argnames"
  show_tuple_as_call(::IO, ::Symbol, ::Type, ::Any, ::Any) at show.jl:2218 got unsupported keyword arguments "demangle", "argnames"
  ...
Stacktrace:
  [1] 
SYSTEM (REPL): caught exception of type MethodError while trying to handle a nested exception; giving up
```

**Comment by BioTurboNick** [comment]
Got it, thanks!

**Comment by BioTurboNick** [comment]
I thought a bit more about `error` and think it's maybe too much to scrub it. There could theoretically be an unrelated error in error itself. And just hiding a single frame doesn't save us screen space. Probably more trouble than it's worth.
