### ISSUE TITLE
text/html stacktraces

### ISSUE THREAD

**Issue by cmcaine** [BioTurboNick/AbbreviatedStackTraces.jl#2]
Stacktraces could use `<display>` or other handy tags to hide likely irrelevant info when displayed in html environments.

Could use other markup to make the errors a bit easier to read, too.

**Comment by BioTurboNick** [comment]
I'm not familiar with those environments, though that sounds like a useful idea! I think it's beyond the scope of what I want to do here, though I'll keep this open so the idea is out there. :-)

**Comment by BioTurboNick** [comment]
I'm going to close this as not in scope for this package. The intent is to make REPL usage easier. Other display pathways can do their own thing, or build on top of this.
