### ISSUE TITLE
Release?

### ISSUE THREAD

**Issue by briochemc** [BioTurboNick/AbbreviatedStackTraces.jl#21]
I understand the goal is to eventually get this into Julia's default, but wouldn't it help to release this as a package for now?

**Comment by BioTurboNick** [comment]
I'm not sure. I'm basically just overwriting a host of Base methods to do this. That feels like bad form?

**Comment by briochemc** [comment]
Oh I'm not sure either! 🤷 Feel free to close this! 😃

**Comment by BioTurboNick** [comment]
Yeah, I'll leave it out for the time being. Thanks for raising the issue though!
