### ISSUE TITLE
precompile on Julia v1.8

### ISSUE THREAD

**Issue by cnrrobertson** [BioTurboNick/AbbreviatedStackTraces.jl#39]
Since Julia v1.8 aims to incrementally precompile modules, importing this package in my `startup.jl` causes a little `Info` warning every time I start a REPL that `AbbreviatedStackTraces` is skipping precompilation. Not a big nuisance but it has made me curious as to why `__precompile__(false)` is necessary for this amazing package.

**Comment by BioTurboNick** [comment]
Warnings are emitted when you load code that overwrites existing methods in other modules, and this stops the warning. If you find a way around that, please let me know.

**Comment by cnrrobertson** [comment]
Ah yes, I see. The only way I know of getting around that would be to use a package like [Suppressor.jl](https://github.com/JuliaIO/Suppressor.jl). It has an `@suppress` macro that you can place in front of the function definitions in `AbbreviatedStackTraces.jl` to catch the warnings from stdout. However, this would add an additional dependency to the package and hide the fact that incremental precompilation isn't functioning for those functions.

If you would like to use `Suppressor.jl`, I've already tested to make sure it would work and would be happy to submit the PR.

**Comment by BioTurboNick** [comment]
Thanks for checking! I'm not sure. My view is that this functionality should be put into Base, and this package is only a demonstration. One of the reasons I have to overwrite the whole chain is that it seems the way these functions are integrated makes them resistant to using the new versions of functions. But overwriting these whole functions could be problematic if they change in Base but aren't kept in sync.

**Comment by BioTurboNick** [comment]
I think the best solution would be for Julia to stop repeatedly trying to precompile packages that have deliberately disabled precompilation. https://github.com/JuliaLang/julia/issues/47123

So I'm going to close this as something I won't fix, but I appreciate the suggestion!

**Comment by BioTurboNick** [comment]
Actually, turns out there's another fix, which is coming -- sticking the code inside `__init__()` avoids the issue.

**Comment by sloede** [comment]
What's the status of this fix? I would really appreciate avoiding the visual noise of this otherwise great package!

**Comment by BioTurboNick** [comment]
Sorry for not updating this issue - turned out that other idea still didn't work.

See: https://github.com/JuliaLang/julia/issues/47123#issuecomment-1275614507
