### ISSUE TITLE
Make the code clearer about what is being overwritten

### ISSUE THREAD

**Issue by KristofferC** [BioTurboNick/AbbreviatedStackTraces.jl#52]
I think it would be good to split out all the functions that are overwriting methods in Base/REPL into their own file and all the auxiliary stuff into another file. Then you could enable precompilation on this package but include the file that overwrites method in the `__init__` function.

**Comment by BioTurboNick** [comment]
I recall putting code in `__init__` prevents Revise from working and `include` has different path behavior, but I'm happy to separate the parts as best I can.

**Comment by BioTurboNick** [comment]
Reorg done, but I'll leave open if there are any better solutions than disabling precompilation or having warnings.

**Comment by BioTurboNick** [comment]
Fixed in v0.1.10

**Comment by BioTurboNick** [comment]
Fixed in v0.1.10
