### ISSUE TITLE
Using `AbbreviatedStackTraces` in another module breaks precompilation

### ISSUE THREAD

**Issue by jonniediegelman** [BioTurboNick/AbbreviatedStackTraces.jl#56]
Something about the recent move of the `include`s to the `__init__` function makes it such that you can't add `AbbreviatedStackTraces` as a dependency for another module. ~~Things work fine if I go back to AbbreviatedStackTraces v0.1.9.~~ EDIT: Turns out that only fixes it at one level. If I have another package that depends on the package that depends on `AbbreviatedStackTraces`, it breaks even on AbbreviatedStackTraces v0.1.9.

Reproducer:
```julia
(@v1.8) pkg> generate Blah

(@v1.8) pkg> activate Blah

(Blah) pkg> add AbbreviatedStackTraces
```
Then editing `src/Blah.jl` to look like this
```julia
module Blah
using AbbreviatedStackTraces
end
```
and precompiling gives the following error:
```julia
(Blah) pkg> precompile
Precompiling project...
  ✗ Blah
  0 dependencies successfully precompiled in 1 seconds. 1 already precompiled.

ERROR: The following 1 direct dependency failed to precompile:

Blah [501caa54-5604-45a8-b8b7-ddcb4fd2be46]

Failed to precompile Blah [501caa54-5604-45a8-b8b7-ddcb4fd2be46] to /Users/jonnie.diegelman/.julia/compiled/v1.8/Blah/jl_OIpo3S.
ERROR: LoadError: InitError: LoadError: Evaluation into the closed module `AbbreviatedStackTraces` breaks incremental compilation because the side effects will not be permanent. This is likely due to some other module mutating `AbbreviatedStackTraces` with `eval` during precompilation - don't do this.
Stacktrace:
  [1] include(mod::Module, _path::String)
    @ Base ./Base.jl:419
  [2] include
    @ ~/.julia/packages/AbbreviatedStackTraces/tYd7d/src/AbbreviatedStackTraces.jl:1 [inlined]
  [3] __init__()
    @ AbbreviatedStackTraces ~/.julia/packages/AbbreviatedStackTraces/tYd7d/src/AbbreviatedStackTraces.jl:200
  [4] _include_from_serialized(pkg::Base.PkgId, path::String, depmods::Vector{Any})
    @ Base ./loading.jl:831
  [5] _require_search_from_serialized(pkg::Base.PkgId, sourcepath::String, build_id::UInt64)
    @ Base ./loading.jl:1039
  [6] _require(pkg::Base.PkgId)
    @ Base ./loading.jl:1315
  [7] _require_prelocked(uuidkey::Base.PkgId)
    @ Base ./loading.jl:1200
  [8] macro expansion
    @ ./loading.jl:1180 [inlined]
  [9] macro expansion
    @ ./lock.jl:223 [inlined]
 [10] require(into::Module, mod::Symbol)
    @ Base ./loading.jl:1144
 [11] include
    @ ./Base.jl:419 [inlined]
 [12] include_package_for_output(pkg::Base.PkgId, input::String, depot_path::Vector{String}, dl_load_path::Vector{String}, load_path::Vector{String}, concrete_deps::Vector{Pair{Base.PkgId, UInt64}}, source::Nothing)
    @ Base ./loading.jl:1554
 [13] top-level scope
    @ stdin:1
in expression starting at /Users/jonnie.diegelman/.julia/packages/AbbreviatedStackTraces/tYd7d/src/override-vscode.jl:1
during initialization of module AbbreviatedStackTraces
in expression starting at /Users/jonnie.diegelman/Blah/src/Blah.jl:1
in expression starting at stdin:1
```

**Comment by BioTurboNick** [comment]
Yeah... `include` really isn't meant to be used from inside a function. I noticed this when trying to use it in another package. I've complained about it. I thought it would work out here though because I didn't imagine anyone would use this one inside another package.

Why do you want to include it in a package, if you don't mind me asking?

**Comment by jonniediegelman** [comment]
We maintain an internal flight simulation that gets used by a lot of people in our company who aren't very familiar with Julia. I'd like to be able to just override the default for everyone when they use our sim so they don't get the typical full-REPL-filling stacktraces when they hit an error. It's been a major stumbling block. Many people on our team would rather write 100s of lines of Rust to do things we've already implemented in Julia just so they don't have to deal with the stacktraces.

**Comment by BioTurboNick** [comment]
With respect to v0.1.9 - precompilation will fail, but there shouldn't be an error. I can't reproduce any bigger problem there, but possible I'm misunderstanding your description?

I will use your testimony in support of getting this functionality into Base, if that's alright?

You may consider using TruncatedStacktraces.jl: https://github.com/SciML/TruncatedStacktraces.jl, which is meant for package authors to control their own stacktraces.

**Comment by BioTurboNick** [comment]
But if you ask, I'll revert back to the non-init version.

**Comment by jonniediegelman** [comment]
> With respect to v0.1.9 - precompilation will fail, but there shouldn't be an error. I can't reproduce any bigger problem there, but possible I'm misunderstanding your description?

Oh yeah, it won't let me use the package either. Doing `using Blah` hits the error for me.

> I will use your testimony in support of getting this functionality into Base, if that's alright?

Yeah, definitely! Thanks. And I appreciate you making this package to address it too. For my personal workflow, it works really well.

> You may consider using TruncatedStacktraces.jl

I'll check that out again. When I tried it the first time, it took a couple minutes to print my first stacktrace from a simulation, so I kinda gave up. But I might have had something working wrong there. It's worth retrying.

> But if you ask, I'll revert back to the non-init version.

I'll try to get `TruncatedStacktraces` working first and see if that will work for me. Thanks.

**Comment by BioTurboNick** [comment]
I'm actually just reverting that anyway - putting those includes in a function breaks Revise.

**Comment by JeffBezanson** [comment]
> We maintain an internal flight simulation that gets used by a lot of people in our company who aren't very familiar with Julia. I'd like to be able to just override the default for everyone when they use our sim so they don't get the typical full-REPL-filling stacktraces when they hit an error. It's been a major stumbling block. Many people on our team would rather write 100s of lines of Rust to do things we've already implemented in Julia just so they don't have to deal with the stacktraces.

This is very interesting. I would like to understand it better. Is it that most/all of the errors can be caught at compile time, so there are no runtime errors? Or does rust do something different with stack traces? Is it that scrolling is a nuisance, which might be fixed e.g. by reversing the order of frames and putting the error message at the bottom?

**Comment by jonniediegelman** [comment]
Scrolling might be the main nuisance. But I think the big difference between Rust and Julia isn't the actual error printing, but that it's a more common practice in Julia to just parameterize everything. Any language whose culture encouraged heavy use of parameterized types would probably have similarly difficult stacktraces.

For us specifically, most of the errors are wrapped in DifferentialEquations internal calls, which are notorious for their long stacktraces due to the parameterization of all of the internal structs it defines. It's especially bad when using ComponentArrays as the state vector, which we also do, because those are really deeply parameterized. Those two combined with a fairly complicated model tree for our simulations means that stacktraces often just fill up the entire REPL and you can't scroll up to see the error.

**Comment by jonniediegelman** [comment]
I mention Rust specifically not because their error messages are particularly good (although they are) or because they tend to catch things at compile time, but mostly just because that's what the majority of people at our company spend most of their time working in.

**Comment by JeffBezanson** [comment]
Thank you!

> DifferentialEquations internal calls, which are notorious for their long stacktraces due to the parameterization of all of the internal structs it defines

Aha! As of v1.10 we have fixed this by limiting the printed depth of types in stacktraces. In fact it was motivated by DifferentialEquations. Have you seen a recent stacktrace? I think you will like it.
