### ISSUE TITLE
Info message every time I start julia

### ISSUE THREAD

**Issue by haakon-e** [BioTurboNick/AbbreviatedStackTraces.jl#58]
I have added `AbbreviatedStackTraces.jl` to my global environment, and the line `using AbbreviatedStackTraces` to my `startup.jl` file. Ever since (I think), Julia 1.9, I get the following `@info` messages whenever I start a Julia session:
```julia
me@dhcp-72-191 folder % julia
[ Info: Precompiling AbbreviatedStackTraces [ac637c84-cc71-43bf-9c33-c1b4316be3d4]
[ Info: Skipping precompilation since __precompile__(false). Importing AbbreviatedStackTraces [ac637c84-cc71-43bf-9c33-c1b4316be3d4].
               _
   _       _ _(_)_     |  Documentation: https://docs.julialang.org
  (_)     | (_) (_)    |
   _ _   _| |_  __ _   |  Type "?" for help, "]?" for Pkg help.
  | | | | | | |/ _` |  |
  | | |_| | | | (_| |  |  Version 1.9.1 (2023-06-07)
 _/ |\__'_|_|_|\__'_|  |  Official https://julialang.org/ release
|__/                   |

julia> 
```

Is this expected, and should I just ignore it? Or should I consider another approach for loading this package?

<details> <summary> versioninfo()  </summary>

```julia
julia> versioninfo()
Julia Version 1.9.1
Commit 147bdf428cd (2023-06-07 08:27 UTC)
Platform Info:
  OS: macOS (arm64-apple-darwin22.4.0)
  CPU: 8 × Apple M1
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-14.0.6 (ORCJIT, apple-m1)
  Threads: 1 on 4 virtual cores
Environment:
  JULIA_EDITOR = code
```

</details>

**Comment by BioTurboNick** [comment]
Unfortunately this is unavoidable. Trying to remove it just causes more pain. It shouldn't have any negative effect other than being ugly though.

**Comment by haakon-e** [comment]
Okay, thanks for the info. It's good to know it's expected, at least. 

edit: this is probably not recommended, but an aesthetic workaround is this:
```julia
using Suppressor
@suppress using AbbreviatedStackTraces
```
