### ISSUE TITLE
Full stacktrace still shown when running `pkg>test` on package

### ISSUE THREAD

**Issue by alecloudenback** [BioTurboNick/AbbreviatedStackTraces.jl#59]
When I run the testset from the VSCode REPL for my package,I still see full stacktraces in the REPL. Manually executing something in the REPL does show an AbbreviateStackTrace.

**Comment by BioTurboNick** [comment]
This is by design by default, as consensus seemed to be that non-interactive uses, like the test runner or distributed workers, would be better to show everything. If you'd like to turn it on for all traces though, you can use `ENV["JULIA_STACKTRACE_ABBREVIATED"] = true`
