### ISSUE TITLE
Use Ctrl+q to display last error

### ISSUE THREAD

**Issue by antoine-levitt** [BioTurboNick/AbbreviatedStackTraces.jl#8]
Relevant code in REPL.jl/setup_interface

**Comment by carstenbauer** [comment]
Good idea. Note though that CTRL+q specifically might be a dangerous choice as it might overlap with "quit this application" for some OSs.

**Comment by antoine-levitt** [comment]
I'm saying ctrl q because julia already uses it for "jump to stack trace". Nobody has complained before, but maybe because people don't know it's there?

**Comment by BioTurboNick** [comment]
FWIW I don't know about it, and it doesn't do anything for me in WSL, Julia on Windows, or in VSCode.

**Comment by antoine-levitt** [comment]
You have to input a number, then press ctrl q, it'll jump on your editor to the definition

**Comment by BioTurboNick** [comment]
If someone wishes to do a pull request for this, I'll merge it.

**Comment by BioTurboNick** [comment]
I'm going to close this as not planned for this package, and we have `err` global now.
